// <auto-generated />
namespace SchoolSolution.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Initial32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial32));
        
        string IMigrationMetadata.Id
        {
            get { return "201310200559307_Initial32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
